/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import "@/olaSDK/style.css"



export const metadata: Metadata = {
  title: "JalSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
      <body
        className={''}
      >

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
